### ISSUE TITLE
idk if this is right one .....

### ISSUE THREAD

**Issue by ninetynin** [AryamannNingombam/portfolio-v2#1]
![image](https://user-images.githubusercontent.com/91336664/159551012-d1d4a769-ed86-4984-8d08-22971b05443f.png)
Im keeping here because the main potfolio website might be private and i cant find another correct place to keep this..... but i think this above image explain the issue

**Comment by Arushigandhi** [comment]
![image](https://user-images.githubusercontent.com/75487137/159626941-e136371f-8a8c-4bd4-8755-942bc6fa239a.png)
yes this is a big issue, pls resolve

**Comment by ninetynin** [comment]
![image](https://user-images.githubusercontent.com/91336664/159628794-538d441a-c657-4efc-974e-741e87a24198.png)
and for logo too i forgot to mention it....

**Comment by AryamannNingombam** [comment]
thanks, added the background, resolved :)

**Comment by ninetynin** [comment]
> thanks, added the background, resolved :)

ya and this website is not supported for mobile phones right?

![image](https://user-images.githubusercontent.com/91336664/160822707-2580652e-e208-47b0-9291-8cd2c22ff7ae.png)
![image](https://user-images.githubusercontent.com/91336664/160822761-1b6cd1fc-5b6c-40f7-8664-745a37deabbf.png)

**Comment by AryamannNingombam** [comment]
hey, no i still have to do that, have not been able to give time lately
